# Generated by Django 2.1.1 on 2018-09-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='App_Users',
        ),
    ]
